name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: 'lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run eslint
        run: yarn run eslint
  unit:
    name: 'unit'
    needs: [lint]
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
        with:
          globalPackages: codecov
      - name: Run test
        run: yarn run -s test:front && codecov -C -F front
